config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :videos
  resources :rates, only: [:create, :destroy]

    
  root :to => 'user_sessions#new'
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!

	has_many :videos
	has_many :rates
	has_many :comments

	validates :email, uniqueness: true
end

app/models/video.rb
class Video < ActiveRecord::Base
	mount_uploader :content, ContentUploader
  has_many :rates
  has_many :comments
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

  private
    def not_authenticated
      redirect_to login_path, alert: "Please login first"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to video_path(params[:comment][:video_id])
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment.update(comment_params)
    redirect_to video_path(params[:comment][:video_id])
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    redirect_to video_path(@comment.video_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :user_id, :video_id)
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def create
    @rate = current_user.rates.create(video_id: params[:video_id])
    redirect_to video_path(params[:video_id])
  end

  def destroy
  	@rate= Rate.find(params[:id])
    @rate.destroy
  	redirect_to video_path(@rate.video_id)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to videos_path
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:new, :create]
  # GET /users
  # GET /users.json
  #def index
   # @users = User.all
  #end

  # GET /users/1
  # GET /users/1.json
  def show
    @videos = @user.videos.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        @user = login(params[:user][:email], params[:user][:password])
        redirect_to videos_path
      else
        render "new"
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :maker)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @rates = @video.rates.find_by_user_id(current_user)
    @comments = @video.comments
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :content, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= f.text_field :video_id, type: "hidden" %>
  
  
    <%= f.text_field :user_id, type: "hidden" %>
  
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Редактировать комментарий:</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MAKERS</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <!-- NAV BAR -->
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Makers", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Все видеоролики", videos_path %></li>
          <li><%= link_to "Пользователь вошел как: #{ current_user.email }" , user_path(current_user) %></li>
          <li><%= link_to "Выход", logout_path, method: "post" %></li>
        <% else %>
          <li><%= link_to "Регистрация", new_user_path %></li>
          <li><%= link_to "Вход", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <!-- NAV BAR -->
    <%= yield %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password, "Пароль" %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Войти" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
<h1>Вход</h1>

<%= render 'form' %>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "Email:" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Пароль:" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
   <%= f.label :password_confirmation, "Подтвердите пароль:" %><br />
   <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :maker, "Добавлять свои видеоролики" %><br>
    <%= f.check_box :maker %>
  </div>
  <div class="actions">
    <%= f.submit "Создать" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<h1>Редактирование пользователя</h1>

<%= render 'form' %>
<br>
<%= link_to "Назад", user_path(current_user), 
 					        class: "btn btn-primary btn-xs", 
 					        role: "button"  %>
</div>

app/views/users/new.html.erb
<div class="container">
<h1>Регистрация</h1>

<%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h4>Информация о пользователе</h4>
<%= link_to "Редактировать пользователя", edit_user_path(current_user), 
 					        class: "btn btn-primary btn-xs", 
 					        role: "button"  %>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Можно загружать ролики?</strong>
  <% if @user.maker %>
    ДА
  <% else %>
    НЕТ
  <% end %>
</p>

<h4>Мои видеоролики:</h4>
<% if @videos.any? %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Creator</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td>
        <% if video.user %>
          <%= video.user.email %>
        <% end %>
        </td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if current_user.maker %> 
 <h4>Загрузить новое видео:</h4>
  <%= form_for Video.new do |f| %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :content %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <%= f.text_field :user_id, type: "hidden", value: current_user.id %>
  
  <div class="actions">
    <%= f.submit "Добавить видос!" %>
  </div>
  <% end %>

<% end %>
</div>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :content %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Список видеороликов</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Creator</th>
      <th>Description</th>
      
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.title, video_path(video) %></td>
        <td><%= video_tag video.content, :size => "320x240", :controls => true %></td>
        <td>
        <% if video.user %>
          <%= video.user.email %>
        <% end %>
        </td>
        <td><%= video.description %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <%= video_tag @video.content, :size => "320x240", :controls => true %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @video.user.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
	<% if @rates %>
	  <%= link_to "Не нравится!", rate_path(@rates), method: :delete %>
	<% else %>
    <%= link_to "Нравится!", rates_path(video_id: @video), method: :post %>
	<% end %>
	(<%= @video.rates.count %>)
</p>

<% if @video.user == current_user %>
  <%= link_to 'Редактировать', edit_video_path(@video) %> |
  <%= link_to 'Back', videos_path %>
<% end %>

<h4>Комментарии (<%= @comments.count %>):</h4>
  <% @comments.each do |comment| %>
    <p>Пользователь <%= comment.user.email %> пишет:</p>
    <p><%= comment.text %></p>
    <% if comment.user_id == current_user.id %>  
      <%= link_to 'Редактировать', edit_comment_path(comment) %>
      <%= link_to 'Удалить', comment_path(comment), 
                                 method: :delete, 
                                 data: { confirm: 'Are you sure?' } %>
    <% end %>  
  <% end %>

<h4>Добавить комментарий:</h4>
  <%= form_for Comment.new do |f| %>
  
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  
  <%= f.text_field :user_id, type: "hidden", value: current_user.id %>
  <%= f.text_field :video_id, type: "hidden", value: @video.id%>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>